[build]
  # Directory con i file di build per il deployment
  publish = "build/web"
  
  # Comando per costruire il progetto Flutter per il web
  command = "flutter build web --release"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
