name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Autorizzazione esplicita per scrivere sul repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable web
        run: flutter config --enable-web
        
      - name: Build web
        run: flutter build web --release --base-href /pescivendolo/
        
      # Aggiunta del file .nojekyll per evitare che GitHub Pages elabori il sito con Jekyll
      - name: Add .nojekyll file
        run: touch build/web/.nojekyll
        
      # Usa un'azione più affidabile per il deploy su gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web   # La cartella da pubblicare
          branch: gh-pages    # Il branch di destinazione
          clean: true         # Rimuove i file che non fanno parte della build
